# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 032b463d1a607a40e993df542f858385fb0252637abe442435ba34eb0508e1a9243cf7201e67317d6c912864c3b98c45806ef7884c59480ca19e75afdb45a0b4

test:
  secret_key_base: 973877d4f66f710e744c8ea09744cab240f9fe4735f0b8955311e30cf023e5e28204309b7569ca0444c063a6220d7ee3b83db91d37b7c609037145e7fa8a5680

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
